---

# Note: Try and limit these to packages that are distro-specific, and
# place commonly-named ones below.
- name: Install distro-specific prerequisites
  include_tasks: "{{ ansible_distribution|lower }}.yml"

- name: Install common support packages
  package:
    name:
      - jq
      - tar
      - curl
      - unzip
      - fontconfig
      - python-psycopg2

- name: Create product group
  group:
    name: "{{ atl_product_user }}"
    gid: "{{ atl_product_user_uid }}"

- name: Create product user
  user:
    name: "{{ atl_product_user }}"
    uid: "{{ atl_product_user_uid }}"
    group: "{{ atl_product_user }}"
    comment: "Product runtime user"
