---

- name: Create mountpoint
  file:
    state: directory
    path: "{{ atl_shared_mountpoint }}"
    mode: 0755

- name: Enable mountpoint in fstab
  mount:
    path: "{{ atl_shared_mountpoint }}"
    src: "{{ efs_target }}:{{ efs_src_dir }}"
    fstype: "{{ efs_type }}"
    opts: "{{ efs_mount_options }}"
    state: mounted
