---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "crowd"
    atl_product_edition: "crowd"
    atl_product_user: "crowd"
    atl_download_format: "tarball"
  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
