---
- hosts: aws_node_local
  become: true

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "crowd"
    atl_product_user: "crowd"
    atl_product_edition: "crowd"
    atl_use_system_jdk: true
    atl_download_format: "tarball"

    atl_startup_systemd_params:
      - "Environment=JDBC_DRIVER={{ atl_db_driver }}"
      - "Environment=JDBC_DIALECT=org.hibernate.dialect.PostgreSQLDialect"
      - "Environment=JDBC_USER={{ atl_jdbc_user }}"
      - "Environment=JDBC_PASSWORD={{ atl_jdbc_password }}"
      - "Environment=JDBC_URL={{ atl_jdbc_url }}"

  roles:
    - role: linux_common
    - role: aws_common
    - role: aws_shared_fs_config
    - role: product_common
    - role: product_install
      tags: [skip_on_stack_update]
    - role: database_init
      tags: [skip_on_stack_update]
    - role: crowd_config
    - role: product_startup
