---
- hosts: aws_node_local
  become: true

  vars:
    # See group_vars/aws_node_local.yml, which pull vars from the environment.
    atl_product_family: "confluence"
    atl_product_user: "confluence"
    atl_product_edition: "confluence"

    atl_jdbc_encoding: 'utf8mb4'
    atl_jdbc_collation: 'utf8mb4_bin'

  roles:
    - role: linux_common
    - role: aws_common
    - role: aws_shared_fs_config
    - role: product_common
    - role: product_install
      tags: [skip_on_stack_update]
    - role: database_init
      tags: [skip_on_stack_update]
    - role: restore_backups
    - role: confluence_common
    - role: confluence_config
    - role: product_startup
