---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: amazon_linux2
    image: amazonlinux:2
    groups:
      - aws_node_local
    ulimits:
      - nofile:262144:262144
  - name: ubuntu_lts
    image: ubuntu:bionic
    groups:
      - aws_node_local
    ulimits:
      - nofile:262144:262144
provisioner:
  name: ansible
  options:
    skip-tags: runtime_pkg
  lint:
    name: ansible-lint
    options:
      x: ["701"]
  inventory:
    links:
      group_vars: ../../../../group_vars/
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
