---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: amazon_linux2
    image: amazonlinux:2
    groups:
      - aws_node_local
# - name: ubuntu_lts
#   image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["303", "602"]
  inventory:
    links:
      group_vars: ../../../../group_vars/
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
