---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "confluence"
    atl_product_edition: "confluence"
    atl_product_user: "confluence"
    atl_product_version: "latest"
    atl_db_engine: "aurora_postgres"
    atl_db_host: "aurora-postgres-db.ap-southeast-2.rds.amazonaws.com"
    atl_jdbc_db_name: "confluence"
    atl_jdbc_user: 'confluence'
    atl_jvm_heap: 'PLACEHOLDER'
    atl_cluster_node_id: 'FAKEID'
    atl_autologin_cookie_age: "COOKIEAGE"
    atl_local_ipv4: "1.1.1.1"

  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
    - role: confluence_common
    - role: confluence_config
