---

- name: Install AWS support packages
  yum:
    name:
      - amazon-efs-utils
      - amazon-ssm-agent
      - awscli
      - git
      - ec2-utils

- name: Install CloudWatch Agent
  yum:
    name:
      - "{{ aws_cloudwatch_agent_rpm }}"
  when: atl_aws_enable_cloudwatch is defined and atl_aws_enable_cloudwatch
  notify:
    - Enable CloudWatch Agent
