---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "jira"
    atl_product_edition: "jira-core"
    atl_product_user: "jira"
    # NOTE: This should be honoured as it is higher than the cached version below.
    atl_product_version: "7.10.1"

  pre_tasks:
    - name: Create cache dir
      file:
        path: '/media/atl/jira/shared/'
        state: directory
    - name: Seed version
      copy:
        dest: '/media/atl/jira/shared/jira-core.version'
        content: "7.10.2"
        force: false  # For idempotency check

  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
