---

# Mostly for molecule testing, as skip-tags doesn't work with handlers.
atl_startup_enable: true
atl_startup_restart: "{{ lookup('env', 'ATL_STARTUP_RESTART') or true }}"

atl_startup_script_map:
  jira: "bin/start-jira.sh"
  confluence: "bin/start-confluence.sh"
  stash: "bin/start-bitbucket.sh"
  crowd: "start_crowd.sh"

atl_startup_exec_path: "{{ atl_product_installation_current }}/{{ atl_startup_script_map[atl_product_family] }}"
atl_startup_exec_options: ["-fg"]
atl_startup_systemd_params: []

atl_systemd_service_name: "{{ atl_product_edition }}.service"

atl_systemd_service_target: "multi-user.target"
