---
- name: Converge
  hosts: all
  vars:
    atl_product_user: "confluence"
    atl_product_family: "confluence"
    atl_product_edition: "confluence"

    atl_startup_systemd_params:
      - "EnvironmentFile=/etc/atl"
      - "EnvironmentFile=/etc/atl.synchrony"
      - "WorkingDirectory={{ atl_product_installation_current }}/logs/"
    atl_startup_exec_options: []
    atl_startup_exec_path: "{{ atl_installation_base }}/bin/start-synchrony"
    atl_systemd_service_name: "synchrony.service"

    atl_startup_enable: false
    atl_startup_restart: false

  pre_tasks:
    - name: Create systemd dir if necessary
      file:
        path: '/usr/lib/systemd/system/'
        state: directory

  roles:
    - role: product_startup
