---
- name: Converge
  hosts: all
  vars:
    atl_product_user: "testuser"
    atl_product_home: "/opt/atlassian/product"
    atl_product_installation_base: "/opt/atlassian/product/install"
    atl_installer_temp: "/opt/atlassian/temp"
    atl_product_home_shared: "/media/atl/jira/shared"
    atl_product_shared_plugins: "/media/atl/jira/shared/plugins/"
    atl_use_system_jdk: true
  roles:
    - role: linux_common
    - role: product_common
