---

- name: "Install systemd service file"
  template:
    src: "product.service.j2"
    dest: "/usr/lib/systemd/system/{{ atl_systemd_service_name }}"
    owner: root
    group: root
    mode: 0640
  notify:
    - Enable Product
    - Restart Product
