---
- name: Converge
  hosts: all
  vars:
    atl_backup_home_dest: "{{ test_archive }}"
    atl_backup_home_restore_canary_path: '/tmp/canary.tmp'
    atl_backup_id: 'test-backup'
    atl_backup_manifest_url: 'fake_manifest'
    atl_backup_home_is_server: 'false'

    atl_product_edition: 'jira-software'
    atl_product_home_shared: '/media/atl/jira/shared'
    atl_product_user: 'jira'
    atl_product_user_uid: '2001'
    atl_product_version_cache: "{{ atl_product_home_shared }}/{{ atl_product_edition }}.version"

    test_archive: '/tmp/hello.tar.gz'
    test_archive_file: 'hello.txt'
    test_archive_source: '/tmp/hello'
    test_pre_step_prefix: '[PRE-TEST]'
    test_product_version_file: "/tmp/{{ atl_product_edition }}.version"

  pre_tasks:
    - name: "{{ test_pre_step_prefix }} Install tar"
      package:
        state: present
        name: tar

    - name: "{{ test_pre_step_prefix }} Install useradd and groupadd binaries"
      package:
        state: present
        name: shadow-utils

    - name: "{{ test_pre_step_prefix }} Create application group"
      group:
        name: "{{ atl_product_user }}"
        gid: "{{ atl_product_user_uid }}"

    - name: "{{ test_pre_step_prefix }} Create application user"
      user:
        name: "{{ atl_product_user }}"
        uid: "{{ atl_product_user_uid }}"
        group: "{{ atl_product_user }}"

    - block:
        - name: "{{ test_pre_step_prefix }} Create a directory for the shared home archive"
          file:
            path: "{{ test_archive_source }}"
            state: directory
            mode: 0755
        - name: "{{ test_pre_step_prefix }} Create a file in the shared home"
          lineinfile:
            create: yes
            line: 'Hello, world!'
            path: "{{ test_archive_source }}/{{ test_archive_file }}"
            mode: 0640
        - name: "{{ test_pre_step_prefix }} Create the version file in the shared home"
          lineinfile:
            create: yes
            line: '8.5'
            path: "{{ test_product_version_file }}"
            mode: 0640
        - name: "{{ test_pre_step_prefix }} Archive the shared home"
          archive:
            path:
              - "{{ test_archive_source }}"
              - "{{ test_product_version_file }}"
            dest: "{{ test_archive }}"
            owner: "{{ atl_product_user }}"

  tasks:
    - name: Install distro-specific restore support packages
      include_tasks: "../../tasks/{{ ansible_distribution|lower }}.yml"

    - name: Restore shared home
      include_tasks: "../../tasks/home_restore.yml"
