---
- name: Converge
  hosts: all
  vars:
    atl_backup_home_dest: "{{ test_archive }}"
    atl_backup_id: 'test-backup'
    atl_backup_manifest_url: 'fake_manifest'
    atl_backup_home_is_server: 'true'

    atl_product_home_shared: '/media/atl/confluence/shared-home'
    atl_backup_home_restore_canary_path: "{{ atl_product_home_shared }}/canary.tmp"
    atl_product_edition: 'confluence'
    atl_product_user: 'confluence'
    atl_product_user_uid: '2001'
    atl_product_version_cache: "{{ atl_product_home_shared }}/{{ atl_product_edition }}.version"

    test_archive: '/tmp/hello.tar.gz'
    test_archive_file: 'hello.txt'
    test_archive_source: '/tmp/hello'

    test_pre_step_prefix: '[PRE-TEST]'
    test_product_version_file: "/tmp/{{ atl_product_edition }}.version"

  pre_tasks:
    - name: "{{ test_pre_step_prefix }} Install tar and useradd/groupadd binaries"
      package:
        state: present
        name:
          - tar
          - shadow-utils

    - name: "{{ test_pre_step_prefix }} Create application group"
      group:
        name: "{{ atl_product_user }}"
        gid: "{{ atl_product_user_uid }}"

    - name: "{{ test_pre_step_prefix }} Create application user"
      user:
        name: "{{ atl_product_user }}"
        uid: "{{ atl_product_user_uid }}"
        group: "{{ atl_product_user }}"

    - name: "{{ test_pre_step_prefix }} Create a Conf server home directory structure"
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ test_archive_source }}"
        - "{{ test_archive_source }}/attachments"
        - "{{ test_archive_source }}/shared-home"

    - name: "{{ test_pre_step_prefix }} Create files"
      copy:
        dest: "{{ item }}"
        content: "content"
      with_items:
        - "{{ test_archive_source }}/unwanted.txt"
        - "{{ test_archive_source }}/attachments/image.jpg"
        - "{{ test_archive_source }}/shared-home/shared-content.txt"

    - name: "{{ test_pre_step_prefix }} Archive the shared home"
      archive:
        path:
          - "{{ test_archive_source }}/*"
        dest: "{{ test_archive }}"
        owner: "{{ atl_product_user }}"

  tasks:
    - name: Install distro-specific restore support packages
      include_tasks: "../../tasks/{{ ansible_distribution|lower }}.yml"

    - name: Restore shared home
      include_tasks: "../../tasks/home_restore.yml"
