---
- name: Converge
  hosts: all
  vars:
    atl_product_edition: "jira-servicedesk"
    atl_product_family: "jira"
    atl_product_user: "jira"
    atl_product_version: "latest"

  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
