---
- name: Converge
  hosts: all
  vars:
    atl_product_user: "bitbucket"
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"

    atl_product_home: "{{ atl_shared_mountpoint }}/{{ atl_product_edition }}"
    atl_product_home_shared: "{{ atl_product_home }}/shared"
    atl_jvm_heap: "dummy_heap"
    atl_jvm_opts: "dummy_opts"

    atl_startup_systemd_params:
      - "UMask=0027"
      - "LimitNOFILE=4096"
      - "Environment=BITBUCKET_HOME={{ atl_product_home }}"
      - "Environment=JVM_MAXIMUM_MEMORY={{ atl_jvm_heap }}"
      - "Environment=JVM_MINIMUM_MEMORY={{ atl_jvm_heap }}"
      - "Environment=JVM_SUPPORT_RECOMMENDED_ARGS={{ atl_jvm_opts }}"

    atl_startup_exec_options:
      - "-fg"
      - "--no-search"

    atl_startup_enable: false
    atl_startup_restart: false

  pre_tasks:
    - name: Create systemd dir if necessary
      file:
        path: '/usr/lib/systemd/system/'
        state: directory

  roles:
    - role: product_startup
